# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNInLocoMediaSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNInLocoMediaSample

  pod 'InLocoMedia-iOS-SDK', '~> 4.2.0'
  pod 'InLocoMedia-iOS-AdMob-Mediation','~> 4.0.0'
  pod 'Google-Mobile-Ads-SDK'

end